# Generated by Django 5.2.9 on 2025-12-27 10:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NetworkNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("factory", "Factory"),
                            ("retail", "Retail Network"),
                            ("entrepreneur", "Individual Entrepreneur"),
                        ],
                        max_length=12,
                        verbose_name="Node Type",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("country", models.CharField(max_length=100, verbose_name="Country")),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                ("street", models.CharField(max_length=150, verbose_name="Street")),
                (
                    "house_number",
                    models.CharField(max_length=10, verbose_name="House Number"),
                ),
                (
                    "level",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="Network Level"
                    ),
                ),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Debt",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplied_nodes",
                        to="network.networknode",
                        verbose_name="Supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Network Node",
                "verbose_name_plural": "Network Nodes",
                "ordering": ["level", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Product Name")),
                ("model", models.CharField(max_length=100, verbose_name="Model")),
                ("release_date", models.DateField(verbose_name="Release Date")),
                (
                    "network_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="network.networknode",
                        verbose_name="Network Node",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["name", "model"],
            },
        ),
    ]
